# Generated by Django 5.0.3 on 2024-04-06 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(9, 58, 0, 719062)),
        ),
    ]
