# Generated by Django 5.0.3 on 2024-03-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, choices=[('US', 'United States'), ('UK', 'United Kingdom'),
                                                                  ('CA', 'Canada')], max_length=2, null=True)),
                ('bio', models.TextField(blank=True)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
