# Generated by Django 5.0.3 on 2024-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True,
                                   choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('PRO', 'Professional')],
                                   max_length=3, null=True),
        ),
    ]
