# Generated by Django 5.0.3 on 2024-03-12 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0004_rename_google_id_profile_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_id',
            new_name='google_id',
        ),
    ]
