# Generated by Django 5.0.3 on 2024-03-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='events',
            field=models.TextField(default=''),
        ),
    ]
