# Generated by Django 5.0.3 on 2024-03-29 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0010_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
