# Generated by Django 5.0.3 on 2024-03-29 14:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0011_task_last_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(14, 26, 53, 262174)),
        ),
    ]
