# Generated by Django 5.0.3 on 2024-03-30 15:27

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0013_remove_task_date_alter_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(15, 27, 53, 202446)),
        ),
    ]
