# Generated by Django 5.0.3 on 2024-03-30 15:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0014_remove_video_create_at_remove_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(15, 31, 17, 651315)),
        ),
    ]
