# Generated by Django 5.0.3 on 2024-03-30 15:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0015_video_image_alter_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(15, 37, 14, 456768)),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(default='bg.jpg', upload_to='images/'),
        ),
    ]
