# Generated by Django 5.0.3 on 2024-03-31 18:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0017_remove_video_image_video_image_url_alter_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(18, 40, 46, 469905)),
        ),
    ]
