# Generated by Django 5.0.3 on 2024-04-02 15:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0030_profile_profile_picture_alter_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(15, 14, 18, 274607)),
        ),
    ]
