# Generated by Django 5.0.3 on 2024-04-03 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WEB', '0035_taskcategory_alter_task_time_task_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
