# Generated by Django 5.0.4 on 2024-04-16 18:17

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0038_remove_video_create_at_remove_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='video',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default='default.mp4', upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=0, upload_to='image/'),
            preserve_default=False,
        ),
    ]
