# Generated by Django 5.0.3 on 2024-04-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='is_joined',
            field=models.BooleanField(default=False),
        ),
    ]
